name: flutter_exif_rotation
description:
  Flutter plugin that fixes the picture orientation when it's took in landscape for some devices.
version: 0.5.1
homepage: https://github.com/NGhebreial/flutter_exif_rotation
repository: https://github.com/NGhebreial/flutter_exif_rotation

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=1.13.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.flutterexifrotation
        pluginClass: FlutterExifRotationPlugin
      ios:
        pluginClass: FlutterExifRotationPlugin
